# PyTorch Lesson 5


Things we will learn in this lesson:

    - How to use softmax function for multi-class classifiction
    - learn how to use the inbuilt dataset from torch
    - Build simple neural network using pytorch
    - customize neural network build for single, multiple dimensions and also for multiple output
    - exploring multiple activation function and their drawbacks and solutions
    

SoftMax function is a function which finds the most probable class among the multiple classes available for classification

> **y = argmax{w*x +b}**

The output for each class (in a multi class setup)
    
    - is binary case the output is between 0 and 1 in effect to sigmoid function
    - where as in a multi class set up, there is no sigmid function so outputs are in diff scale and it's therfore important to bring all the class probabilities into one scale for comparison
    - once the values are brought into scale they can now be comapred and argmax can be performed to choose the most probable class to the particular sample under test
    
    

In [197]:
from torch import nn
import torch
class softmax(nn.Module):
    def __init__(self,in_,out_):
        super(softmax,self).__init__()
        self.Linear = nn.Linear(in_,out_)
    def forward(self,x):
        return self.Linear(x)

In [49]:
x = torch.arange(-3,3,0.2)

f = -3*x

y = f+(0.1*torch.rand(x.shape[0],1)).reshape(-1)


In [50]:
model.state_dict()

OrderedDict([('Linear.weight', tensor([[ 0.9640],
                      [ 0.6772],
                      [-0.1357]])),
             ('Linear.bias', tensor([ 0.1914, -0.0856, -0.5479]))])

In [52]:
x

tensor([-3.0000, -2.8000, -2.6000, -2.4000, -2.2000, -2.0000, -1.8000, -1.6000,
        -1.4000, -1.2000, -1.0000, -0.8000, -0.6000, -0.4000, -0.2000,  0.0000,
         0.2000,  0.4000,  0.6000,  0.8000,  1.0000,  1.2000,  1.4000,  1.6000,
         1.8000,  2.0000,  2.2000,  2.4000,  2.6000,  2.8000])

In [55]:
model = softmax(1,3)
yhat = model.forward(x.view(-1,1))

##argmax of the predicted probabilities(shown without optimization just as an example)
yhat.max(1)

(tensor([-2.2666, -2.1496, -2.0327, -1.9157, -1.7988, -1.6818, -1.5578, -1.4061,
         -1.2545, -1.1028, -0.9512, -0.7995, -0.6479, -0.4962, -0.3446, -0.1929,
         -0.0413,  0.1104,  0.2621,  0.4137,  0.5654,  0.7170,  0.8687,  1.0203,
          1.1720,  1.3236,  1.4753,  1.6269,  1.7786,  1.9302],
        grad_fn=<MaxBackward0>),
 tensor([2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]))

To use softmax function along with the loss we will us e special function

**nn.CrossEntropyLoss --> this method does Entropy loss and apply softmax function on top**

### How to donwload a dataset from PyTorch

In [74]:
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.datasets as dsets
from torch.utils.data import Dataset, DataLoader
from torch import optim

In [75]:
loss = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [68]:
train = dsets.MNIST(root='./', train=True, download=True, transform=transforms.ToTensor())
validation = dsets.MNIST(root='./', train=False, download=True, transform=transforms.ToTensor())


0it [00:00, ?it/s]


 61%|█████████████████████████████████████████▏                         | 6086656/9912422 [00:09<00:01, 2034191.51it/s]


100%|██████████████████████████████████████████████████████████████████▋| 9863168/9912422 [00:11<00:00, 2177235.66it/s]

Extracting ./MNIST\raw\train-images-idx3-ubyte.gz to ./MNIST\raw




0it [00:00, ?it/s]



  0%|                                                                                        | 0/28881 [00:00<?, ?it/s]

 85%|█████████████████████████████████████████████████████████████▎          | 24576/28881 [00:00<00:00, 138363.78it/s]


0it [00:00, ?it/s]

Extracting ./MNIST\raw\train-labels-idx1-ubyte.gz to ./MNIST\raw





  0%|                                                                                      | 0/1648877 [00:00<?, ?it/s]


  1%|█                                                                     | 24576/1648877 [00:00<00:13, 120562.74it/s]


  2%|█▍                                                                     | 32768/1648877 [00:01<00:17, 93658.24it/s]


  3%|██                                                                     | 49152/1648877 [00:01<00:19, 81680.39it/s]


  4%|██▊                                                                    | 65536/1648877 [00:01<00:17, 91264.76it/s]


  6%|████▍                                                                | 106496/1648877 [00:01<00:13, 117243.85it/s]


  8%|█████▍                                                               | 131072/1648877 [00:01<00:11, 137620.21it/s]


 12%|████████▏                                                            | 196608/1648877 [00:01<00:08, 178672.00it/s]


 15%|██████████▋     

Extracting ./MNIST\raw\t10k-images-idx3-ubyte.gz to ./MNIST\raw





8192it [00:00, 10831.75it/s]                                                                                           


Extracting ./MNIST\raw\t10k-labels-idx1-ubyte.gz to ./MNIST\raw
Processing...
Done!


In [72]:
train_loader = DataLoader(dataset = train, batch_size=100)
validation_loader = DataLoader(dataset = train, batch_size=5000)

The below piece of code iterates over the number of epoch

For every epoch,

    -train dataset is sent in batches specified in dataloader method
    -loss, backpropagation and weight updation takes place
    -after which validation dataset is validation on the trained model and their correposning accuracy metric is calculated
    -this process is repeated for specified n_epoch(10 here)

In [ ]:
for epoch in range(10):
    for x,y in train_loader:
        optimizer.zero_grad()
        yhat = model.forward(x.view(-1,28*28))
        loss_ = loss(yhat, y)
        loss.backward()
        optimizer.step()
    correct_prediction = 0
    
    for x_test,y_test in validation_loader:
        z = model(x_test.view(-1,28*28))
        _,yhat = torch.max(z.data,1)
        correct_prediction = correct_prediction + (yhat == y_test).sum().item()

    accuracy = correct_prediction/len(x_test)
    accuracy_list.append(accuracy)


# Neural network build

## Neural network with multi-dimensonal input

In [93]:
from torch import nn

class Net(nn.Module):
    def __init__(self,D_in, H, D_out):
        super(Net, self).__init__()
        self.Linear1 = nn.Linear(D_in, H)
        self.Linear2 = nn.Linear(H, D_out)
    def forward_(self,x):
        x = torch.sigmoid(self.Linear1(x))
        x = torch.sigmoid(self.Linear2(x))
        return x

In [120]:
model = Net(1,2,1)

error = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr =0.01)
x = torch.tensor([-3.0])

f = -3*x

y = torch.tensor(-10.0)

In [121]:
cost = []
loss_ = []
for epoch in range(10):
    yhat = model.forward_(x)
    loss = error(yhat, y)
    optimizer.zero_grad()
    loss.backward()
    loss_.append(loss.item())
    optimizer.step()
    print('The cost at the end of epoch{} is {}'.format(epoch,loss.item()))

The cost at the end of epoch0 is 2.75771164894104
The cost at the end of epoch1 is -0.09584802389144897
The cost at the end of epoch2 is -2.9469614028930664
The cost at the end of epoch3 is -5.797658443450928
The cost at the end of epoch4 is -8.649755477905273
The cost at the end of epoch5 is -11.504983901977539
The cost at the end of epoch6 is -14.364992141723633
The cost at the end of epoch7 is -17.23130226135254
The cost at the end of epoch8 is -20.10519027709961
The cost at the end of epoch9 is -22.987611770629883


C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\torch\nn\functional.py:2016: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))


We could claearly see how a neural network id getting built

Summary:
    - for a single scalar input with one sample, we create a 2 linear models in the hidden layer (hence Linear1(1,2))
    - once we built the Linear1 model which outputs two outputs, we pass them through the sigmoid function to add non-linearity
    - These output values are fed to built one linear model (hence Linear2(2,1))
    - The output is passed through sigmoid to have the final predictions
    - the error/loss is then calculated using Binary Cross Entropy 
    - weights are adjusted using differntiation
    - this process is repeated for n epochs

### Overfitting:
    - this occurs when the model is complex than the data (i.e model is built very complex that it learns the entire data by-heart)
    - obviously the model so built has too many neurons
    
### Underfitting:
    - this occurs when a data is more complex than the model built(doesnot learn the basics of the data representation)
    - cause could be very few neurons
    - very less data

**Solution:**
    - use validation data to identify the optimal number of neurons for the specific dataset
    - regularization(dropout)

## Neural network with multi-dimensonal input

In [124]:
from torch import nn

class Net(nn.Module):
    def __init__(self,D_in, H, D_out):
        super(Net, self).__init__()
        self.Linear1 = nn.Linear(D_in, H)
        self.Linear2 = nn.Linear(H, D_out)
    def forward_(self,x):
        x = torch.sigmoid(self.Linear1(x))
        x = torch.sigmoid(self.Linear2(x))
        return x

We create a single sample input with 3 dimensions and its out target as 1

In [147]:
model = Net(3,6,1)

error = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr =0.01)
x = torch.tensor([-3.0,10.0,5.0])

f = -3*x

y = torch.tensor([1.0])

In [148]:
cost = []
loss_ = []
for epoch in range(100):
    yhat = model.forward_(x)
    loss = error(yhat, y)
    optimizer.zero_grad()
    loss.backward()
    loss_.append(loss.item())
    optimizer.step()
    if epoch%10==0:
        print('The cost at the end of epoch{} is {}'.format(epoch,loss.item()))

The cost at the end of epoch0 is 0.45546144247055054
The cost at the end of epoch10 is 0.41135525703430176
The cost at the end of epoch20 is 0.3729822039604187
The cost at the end of epoch30 is 0.3397429883480072
The cost at the end of epoch40 is 0.3108556866645813
The cost at the end of epoch50 is 0.28562384843826294
The cost at the end of epoch60 is 0.2634837031364441
The cost at the end of epoch70 is 0.24398145079612732
The cost at the end of epoch80 is 0.2267438769340515
The cost at the end of epoch90 is 0.21145708858966827


In [149]:
yhat

tensor([0.8194], grad_fn=<SigmoidBackward>)

The prediction is close to 1 

## Neural network with muti-class output

In [169]:
from torch import nn

class Net(nn.Module):
    def __init__(self,D_in, H, D_out):
        super(Net, self).__init__()
        self.Linear1 = nn.Linear(D_in, H)
        self.Linear2 = nn.Linear(H, D_out)
    def forward_(self,x):
        x = torch.sigmoid(self.Linear1(x))
        x = self.Linear2(x) #**remove sigmoid isnce we are applying softmax for multiclass**
        return x

In [186]:
model = Net(3,6,2)

error = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr =0.01)
x = torch.tensor([[-3.0,10.0,5.0],[-1.0,0.0,-5.0],[-2.0,10.0,5.0]])

f = -3*x

y = torch.tensor([[0.],[1.],[0.]])

In [ ]:
cost = []
loss_ = []
for epoch in range(100):
    yhat = model.forward_(x)
    print(yhat)
    print(y)
    loss = error(y, yhat) #cross entrpy loss takes in only long int format **caution
    optimizer.zero_grad()
    loss.backward()
    loss_.append(loss.item())
    optimizer.step()
    if epoch%10==0:
        print('The cost at the end of epoch{} is {}'.format(epoch,loss.item()))

In [175]:
yhat

tensor([[ 0.4629, -0.0914],
        [ 0.3035,  0.0968],
        [ 0.4620, -0.0798]], grad_fn=<AddmmBackward>)

# Popular activation functions are:
    
    - sigmoid (0 to 1 but serious disadvantage of vanishing gradient descent)
    - tanh (-1 to +1)
    - Relu activation

##### Sigmoid activation function with derivative shows that,

the derivating does increase for a moment upto 2.0 but decreases down to zero for higher values of z

Hence suffers **Vanishing gradient Problem**

<img src='./sigmoid.png'>

Lets see how sigmoid is used in pytorch

In [198]:
class NetRelu(nn.Module):    
        def __init__(self,D_in,H,D_out):
            super(NetRelu,self).__init__() 
            self.linear1=nn.Linear(D_in,H)        
            self.linear2=nn.Linear(H,D_out)            
        def forward(self,x):        
            x=torch.sigmoid(self.linear1(x))          
            x=torch.sigmoid(self.linear2(x))     
            return x

##### Tanh activation function with derivative shows that,

the derivating does increase for a moment upto 1.0 but decreases down to zero for higher values of z

Hence suffers **Vanishing gradient Problem**

<img src='./tanh.png'>

In [199]:
class NetRelu(nn.Module):    
        def __init__(self,D_in,H,D_out):
            super(NetRelu,self).__init__() 
            self.linear1=nn.Linear(D_in,H)        
            self.linear2=nn.Linear(H,D_out)            
        def forward(self,x):        
            x=torch.tanh(self.linear1(x))          
            x=self.linear2(x)
            return x

##### Relu activation function with derivative shows that,

the derivative goes to constant 1.0 for all positve values of z

**Vanishing gradient Problem** has a solution NOW!

<img src='./relu.png'>

In [200]:
class NetRelu(nn.Module):    
        def __init__(self,D_in,H,D_out):
            super(NetRelu,self).__init__() 
            self.linear1=nn.Linear(D_in,H)        
            self.linear2=nn.Linear(H,D_out)            
        def forward(self,x):        
            x=torch.relu(self.linear1(x))          
            x=self.linear2(x)
            return x